### ISSUE TITLE
Error creating note and folder

### ISSUE THREAD

**Issue by gurguven** [moki-moki/web-obsi#1]
When clicking buttons in sidebar. 

![image](https://github.com/user-attachments/assets/4248aa1d-bf9a-481c-b264-e6a402c07968)
![image](https://github.com/user-attachments/assets/15d29956-3cac-43ab-9f68-11336c8abe7b)

**Comment by moki-moki** [comment]
Hey,

Can you send me a status code and response to it. I've tried it on my local machine on a completely clean browser, but couldn't replicate the results.


https://github.com/user-attachments/assets/e1c394bb-746d-40f7-bd60-840ba2d89f17
